name: dio_cache_interceptor_hive_store
description: A DB cache store implementation with Hive for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_hive_store
version: 3.2.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor:
    git:
      url: https://github.com/edwinnyawoli/dio_cache_interceptor
      ref: patch_utf_16
      path: dio_cache_interceptor

  # https://pub.dev/packages/hive
  hive: ^2.0.5

# dependency_overrides:
#   dio_cache_interceptor:
#     path: ../dio_cache_interceptor

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^1.0.1
  # https://pub.dev/packages/test
  test: ^1.18.0
