name: dio_cache_interceptor_objectbox_store
description: A DB cache store implementation with ObjectBox for dio_cache_interceptor package.
version: 1.1.0
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_objectbox_store
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor:
    git:
      url: https://github.com/edwinnyawoli/dio_cache_interceptor
      ref: patch_utf_16
      path: dio_cache_interceptor
  # https://pub.dev/packages/objectbox
  objectbox: ^1.4.1
  # https://pub.dev/packages/flat_buffers
  flat_buffers: ^2.0.5

# dependency_overrides:
#   dio_cache_interceptor:
#     path: ../dio_cache_interceptor

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.1.7
  # https://pub.dev/packages/objectbox_generator
  objectbox_generator: any
  # https://pub.dev/packages/lints
  lints: ^1.0.1
  # https://pub.dev/packages/test
  test: ^1.18.0